[TASK] some

diff --git a/remotes b/remotes
--- a/remotes
+++ b/remotes
@@ -2,7 +2,6 @@
 
 set -o errexit
 set -o nounset
-set -o pipefail
 
 RE_VERSION="1.0.0"
 RE_SOURCE_FILE_PATH="${HOME}/.remotes"
@@ -22,24 +21,26 @@ OPTIONS:
     "
 }
 
-# print the given message and exits
+# print the given argumens and exits
 die() {
     echo "${*}" && exit 0
 }
 
+# print the given arguments bold
 bold() {
-    echo "\033[1m${1}\033[0m"
+    printf "\033[1m%s\033[0m" "${*}"
 }
 
 # reads the lines from the remotes file
 read_lines() {
-    if [[ -f "${RE_SOURCE_FILE_PATH}" ]]; then
+    if [ -f "${RE_SOURCE_FILE_PATH}" ]; then
         grep -o '^[^#]*' "${RE_SOURCE_FILE_PATH}"
     else
         die "File ${RE_SOURCE_FILE_PATH} not existing."
     fi
 }
 
+# returns the line specified by the given number
 read_line_from_number() {
     read_lines | sed -n "${1}p"
 }
@@ -51,11 +52,12 @@ print_version() {
 
 # edit the source remotes files
 edit_source_file() {
-    if [[ ! "$(which code)" == "" ]]; then
-        (code "${RE_SOURCE_FILE_PATH}" && exit 0)
-    elif [[ ! "$(which vim)" == "" ]]; then
-        (vim "${RE_SOURCE_FILE_PATH}" && exit 0)
+    if [ ! "$(which code)" = "" ]; then
+        code "${RE_SOURCE_FILE_PATH}"
+    elif [ ! "$(which vim)" = "" ]; then
+        vim "${RE_SOURCE_FILE_PATH}"
     fi
+    exit 0
 }
 
 # lists all remotes
@@ -76,12 +78,12 @@ list() {
 
 connect_to_remote() {
     if [[ ! "${1}" =~ ^[0-9]+$ ]]; then
-        die "Invalid number: ${1}"
+        die "Not a number: ${1}"
     fi
 
     RE_REMOTE=$(read_line_from_number "${1}")
 
-    if [[ "${RE_REMOTE}" == "" ]]; then
+    if [ "${RE_REMOTE}" = "" ]; then
         die "Invalid number: ${1}"
     fi
 
@@ -95,9 +97,10 @@ connect_to_remote() {
 # connect to remote
 connect_interactive() {
     list
-    read -r -p "Enter the number to connect to / $(bold "q") to quit: " RE_ANSWERE
+    printf "Enter the number to connect to / %s to quit: " "$(bold "q")"
+    read -r RE_ANSWERE
 
-    if [[ "${RE_ANSWERE}" == "q" ]]; then
+    if [ "${RE_ANSWERE}" = "q" ] || [ "${RE_ANSWERE}" = "" ]; then
         exit 0
     else
         connect_to_remote "${RE_ANSWERE}"
@@ -105,9 +108,9 @@ connect_interactive() {
 }
 
 # guard existence of argument / command
-[[ $# -ne 0 ]] || connect_interactive
+[ $# -ne 0 ] || connect_interactive
 
-while (($# > 0)); do
+while [ $# -ne 0 ]; do
     opt="${1}"
     shift
 
@@ -128,17 +131,19 @@ while (($# > 0)); do
         print_version
         exit 0
         ;;
-    '' | *[!0-9]*)
-        die "Unknown option: '${opt}'.  Pass '$(bold "--help")' for a list of commands."
+    --number | -n)
+        [ $# -ne 0 ] || die "Missing argument for $(bold "--number | -n") option."
+        RE_NUMBER="${1}"
+        shift
         ;;
     *)
-        RE_NUMBER="${opt}"
+        die "Unknown option: '${opt}'.  Pass '$(bold "--help")' for a list of commands."
         ;;
     esac
 done
 
-if [[ "${RE_NUMBER}" == "" ]]; then
-    die "no number specified"
+if [ "${RE_NUMBER}" = "" ]; then
+    die "No number specified"
 else
     connect_to_remote "${RE_NUMBER}"
 fi
